### ISSUE TITLE
When scikit-umfpack is installed, only a single vector can be given to factorized matrix

### ISSUE THREAD

**Issue by andreasbuhr** [pymor/pymor#341] opened 2016-12-19 13:04 UTC
otherwise
![scipy_umfpack_error](https://cloud.githubusercontent.com/assets/3892222/21313770/fc27b110-c5f3-11e6-9daa-c46f4b6c4eb5.png)

**Comment by sdrave** [comment] 2017-08-09 14:24
Hi @andreasbuhr, do you have a MWE where to reproduce the issue? In the traceback, I cannot see any pyMOR code at all ..

**Comment by sdrave** [comment] 2018-04-18 10:45
Can't reproduces this, at least with current SciPy, scikit-umfpack. Closing.

**Closed by sdrave** 2018-04-18 10:45 UTC
