### ISSUE TITLE
Jupyter matplotlib visualization backend is broken with recent ipywidgets

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#1947] opened 2023-02-06 13:42 UTC
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [6], in <module>
----> 1 m.visualize(U)

File ~/Repos/pymor/src/pymor/models/interface.py:671, in Model.visualize(self, U, **kwargs)
    659 """Visualize a |VectorArray| U of the model's :attr:`solution_space`.
    660 
    661 Parameters
   (...)
    668     See the docstring of `self.visualizer.visualize`.
    669 """
    670 if getattr(self, 'visualizer') is not None:
--> 671     return self.visualizer.visualize(U, **kwargs)
    672 else:
    673     raise NotImplementedError('Model has no visualizer.')

File ~/Repos/pymor/src/pymor/discretizers/builtin/gui/visualizers.py:90, in PatchVisualizer.visualize(self, U, title, legend, separate_colorbars, rescale_colorbars, block, filename, columns)
     88 if self.backend == 'jupyter':
     89     from pymor.discretizers.builtin.gui.jupyter import get_visualizer
---> 90     return get_visualizer()(self.grid, U, bounding_box=self.bounding_box, codim=self.codim, title=title,
     91                             legend=legend, separate_colorbars=separate_colorbars,
     92                             rescale_colorbars=rescale_colorbars, columns=columns)
     93 else:
     94     block = self.block if block is None else block

File ~/Repos/pymor/src/pymor/discretizers/builtin/gui/jupyter/matplotlib.py:150, in visualize_patch(grid, U, bounding_box, codim, title, legend, separate_colorbars, rescale_colorbars, columns)
    145     def __init__(self):
    146         super(Plot, self).__init__(U, grid, codim, legend, bounding_box=bounding_box, columns=columns,
    147                                    separate_colorbars=separate_colorbars, separate_plots=True,
    148                                    separate_axes=False)
--> 150 return Plot()

File ~/Repos/pymor/src/pymor/discretizers/builtin/gui/jupyter/matplotlib.py:146, in visualize_patch.<locals>.Plot.__init__(self)
    145 def __init__(self):
--> 146     super(Plot, self).__init__(U, grid, codim, legend, bounding_box=bounding_box, columns=columns,
    147                                separate_colorbars=separate_colorbars, separate_plots=True,
    148                                separate_axes=False)

File ~/Repos/pymor/src/pymor/discretizers/builtin/gui/jupyter/matplotlib.py:89, in MPLPlotBase.__init__(self, U, grid, codim, legend, bounding_box, separate_colorbars, columns, separate_plots, separate_axes)
     87 plt.close()
     88 # IPython display system checks for presence and calls this func
---> 89 self._ipython_display_ = self._out._ipython_display_

AttributeError: 'Output' object has no attribute '_ipython_display_'
```

**Comment by pmli** [comment] 2023-02-06 20:47
Maybe a duplicate of #1717?

**Closed** 2023-02-14 09:53 UTC
Labels: bug
