### ISSUE TITLE
Systems theory MOR methods

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#291] opened 2016-09-08 13:24 UTC
Hi @sdrave, @ftalbrecht, @renemilk! I think my `lti_sys_mor` branch is ready to be added here as a development branch. There are still some issues to resolve (like #285) and I would very much appreciate your help with adapting to pyMOR's framework (such as using caching, logging...).

How do you suggest to proceed?

**Comment by sdrave** [comment] 2016-09-08 15:39
Hi @pmli, great to hear that! I will take a closer look at your code next week.
I guess it would be nice to have a place where we both have push access. I guess we could add a pymor-sys-mor repo to the pyMOR organization where you have push access as well. Or we wait for your application to become a pyMOR developer ..

**Comment by sdrave** [comment] 2016-10-31 13:49
Hi @pmli, I found some time to take a look at the sys-mor branch. I guess there a several things to discuss before merging into master. For a start, I looked into the `solve_lyap` and `solve_ricc` methods. If I understood the code correctly, with the exemption of the H_infty norm calculation, these are the only places which crucially depend on access to the matrix data?

I had a chat with @ftalbrecht, and we came to the conclusion that it might actually be the best approach to add these methods as optional methods to the `OperatorInterface`. This would have the following adavantages:

- The situation is really analogous to `apply_inverse`: All methods deal with (matrix) equation solvers whose implementation depends on the given matrix data type, so it is natural to dispatch on the `Operator` type.
- In particular we could use `solver_options` to select the specific solver.
- It would remain true that in order to integrate a new high-dimensional solver you only have to implement `OperatorInterface`, `VectorArrayInterface` and `DiscretizationInterface`.

The same discussion would also apply to a `solv_eig` method which we will need sooner or later.

@pmli, if you think this is a good approach, I would try to do the refactoring in a separate branch.

**Comment by pmli** [comment] 2016-11-01 13:28
Hi @sdrave, in `solve_lyap` and `solve_ricc`, some solvers need access to matrix data (`scipy`, `slycot`, `pymess.lyap`, and `pymess.care`), while some only need vector data access (`pymess.lradi` and `pymess.lrnm`). So far, H_infty norm calculation needs matrix data access, hopefully one day it won't.

I don't understand how you would add `solve_lyap` and `solve_ricc` to the `OperatorInterface`. One operator may not be enough to define a matrix equation, e.g. in the Lyapunov equation there might be `A` and `E` (there is also a question of `B`, is it an operator or a vectorarray). Would `E` and `B` be arguments in `A.solve_lyap`?

**Comment by sdrave** [comment] 2016-11-02 12:10
Yes, `E` and `B` would be arguments to the method. I agree that it might be not the most natural approach to have this as a method on `A`, but from it technical nature `solve_lyap` is very similar to `apply_inverse`.

**Comment by pmli** [comment] 2016-11-03 10:06
I find `A.solve_lyap` very unnatural. Matrix equations and their solutions (aka Gramians) are most closely related to systems (i.e. `discretizations`), just as much are system trajectories and transfer function evaluations. To emphasize this in another way, different systems have different Lyapunov equations (and Gramians): LTI systems have "standard" Lyapunov equations, bilinear systems have bilinear Lyapunov equations, linear parametric systems have parametric Lyapunov equations, linear stochastic systems are similar to bilinear system and thus can also have bilinear Lyapunov equations, etc.

I would say `compute_gramian` is very similar to `solve` for discretizations, and `solve_lyap`/`solve_ricc` is very similar to `_solve`.

**Comment by sdrave** [comment] 2016-11-03 12:24
Ok, so attaching the methods to the `Discretization` might be an option as well. 

However, could you elaborate how the various Lyapunov equations differ?

**Comment by pmli** [comment] 2016-11-03 13:45
Basically, as you add more operators to a system, the Lyapunov equation gets longer. For a linear time invariant (LTI) system E x' = A x + B u, y = C x, the controllability Lyapunov equation is A P E<sup>T</sup> + E P A<sup>T</sup> + B B<sup>T</sup> = 0. For a bilinear system E x' = A x + &Sigma;<sub>i</sub> N<sub>i</sub> x u<sub>i</sub> + B u, the controllability Lyapunov equation is A P E<sup>T</sup> + E P A<sup>T</sup> + &Sigma;<sub>i</sub> N<sub>i</sub> P N<sub>i</sub><sup>T</sup> + B B<sup>T</sup> = 0. For a quadratic-bilinear system, you would add another term involving the Hessian.

(M.E.S.S. doesn't have a bilinear Lyapunov equation solver, for now.)

For linear parametric systems, you get the standard Lyapunov equation for any specific choice of the parameter.

For linear time varying (LTV) systems, there are differential Lyapunov equations (P depends on time and a E P' E<sup>T</sup> term appears). Linear parameter varying (LPV) systems can be interpreted as bilinear systems, so you could use bilinear Lyapunov equations. Linear stochastic systems also look like bilinear systems.

I'm not aware of Lyapunov equations for linear delay systems, although something probably exists.

I would also like to point out that there are more versions of Balanced Trucation (BT), which uses standard Lyapunov equations. Actually, just for LTI systems, there are at least 8 other versions of BT, each with its own pair of matrix equations: LQG BT, Balanced Stochastic Truncation, Positive Real BT, Bounded Real BT, H<sub>&infin;</sub> BT, frequency weighted BT, frequency limited BT, and time limited BT.

**Comment by sdrave** [comment] 2016-11-04 12:16
Ok, so if LTI systems are the only place where `solve_lyap` is used in the foreseeable future, I would say we attach the function to the discretization. Regarding the wrapper code for pymess and slycot, see #321.

On a different note, I tried to run the heat.py demo which is failing with an `ImportError: cannot import name 'ab13dd'` after having installed slycot via pip. Any idea what's wrong?

**Comment by pmli** [comment] 2016-11-04 12:51
I'm not so sure about moving `solve_lyap` to `LTISystem` class. Why not have `compute_gramian` for discretizations like `apply_inverse` for `NumpyMatrixOperator`, where `_apply_inverse` is outside the class?

Yes, you need to install slycot from the [current master branch in painyeph/Slycot](https://github.com/painyeph/Slycot/tree/e7dc43676d543e12c50533755bce078eed737aa1).

**Comment by sdrave** [comment] 2016-11-04 13:26
The demo is working now!

Why are you against adding a `_solve_lyap` method to LTISystem`? The advantage of having such a method would be that the user can exchange the Lyapunov solver by subclassing.

**Comment by pmli** [comment] 2016-11-04 16:25
Great!

I wasn't very precise with terminology above. It's not good to say that different systems have "different Lyapunov equations". Lyapunov equation is one thing, bilinear Lyapunov equation is another, quadratic-bilinear Lyapunov equation is yet another thing, etc. On the other hand, a bilinear Lyapunov equation can be solved by solving a sequence of Lyapunov equations (by fixed point iteration, which can be very expensive). There are also truncated (quadratic-)bilinear Gramians, where you specify in advance the length (usually very small, e.g. 2 or 3) of the sequence of Lyapunov equations.

All in all, I think it's correct to say that a system can have different types of Gramians, which are solutions of certain matrix equations, and most of them can be computed using a Lyapunov equation or a Riccati equation solver. This is why I like to have `compute_gramian` method in discretizations and `solve_lyap`/`solve_ricc` somewhere else.

@sdrave Far above, you had a point about integrating new high-dimensional solvers. I didn't understand it. I think that solvers which need vector data access (`pymess.lradi` and `pymess.lrnm`) only expect `data` and `from_data` in the `VectorArrayInterface`.

**Comment by sdrave** [comment] 2016-11-07 13:26
Ok, so maybe I should try to make my point of view more clear:

Currently, pyMOR's main selling point is its ability to interface with external (PDE) solver libraries which provide the high-dimensional models to reduce. This is what I usually mean by 'integrating a new solver'. The integration is achieved by defining clear interfaces which need to be fulfilled by the external code in order to work with pyMOR. Right now these interfaces are `VectorArrayInterface`, `OperatorInterface` or `DiscretizationInterface`, and every reduction algorithm in pyMOR is implemented by means of these interfaces.

For PDE solvers, linear equation system solvers are in many cases part of the PDE solver and are often optimized for the specific problem at hand. Depending on the problem, linear solvers are exposed either via `apply_inverse` on the operators or via `solve` on the discretization.

As we have been discussing, I am willing to add algorithms to pyMOR which directly operate on the matrix data when the need arises. However, when reviewing your code, I was happy to see that nearly all of your code falls into pyMOR's design philosophy, as long as we interpret matrix equation solvers, similar to linear solvers, as part of the interface with the high-dimensional model. Going this route, the question would be how to make access to these matrix equation solvers part of the interface, and the natural answer would be to tie the solver calls to one of the existing interface classes. Which is why I first proposed `OperatorInterface` and then the `Discretization`.

By having a free `solve_lyap` function, there is no way for the user to hook an own Lyapunov solver into pyMOR without directly modifying the source of `solve_lyap`. Even when one would add a way, say by adding a user-modifiable dict of Lyapunov solver implementations, this would add a fourth component to pyMOR's external solver interface. Of course, this is doable, but not very consistent with what we currently have.

It may be true that PDE solvers usually do not come with their own Lyapunov solver implementation and that pymess is a quite generic option. Still, there might be use cases where a custom Lyapunov solver might be required/desired:
- Inclusion of a priori knowledge of the problem at hand.
- If one looks at the pymess interface one obvious place for optimization is `ApEINV_apply` where the user might want to dispatch into an optimized solver for the resolvent operator. Without the possibility to write a custom `LyapunovEquation` class, one would have to implement `assemble_lincomb` to return a specialized operator whose `apply_inverse` method would call the optimized solver. This is probably messy and much more complicated then customizing the solve_lyap call.
- The are scenarios where implementing `data` and `from_data` is simply not an option. In particular, `MPIVectorArray` currently does not implement these methods. An even when: Does pymess work with MPI distributed vector data? (This issue might be mitigated by letting pymess expose a vector interface. I believe, Jens said that this should be possible.)
- Right now, pymess has not been released to the public. Is the license clear? If it's GPL, then using it might be not an option for some users.

How about the following proposal: Let's say we have this `bindings` package (#321). Then there could be `pymor.bindings.slycot.solve_lyap` and a `pymor.bindings.pymess.solve_lyap` (and maybe `pymor.bindings.scipy.solve_lyap`) all with the same signature (except special optional arguments). Then `LTISystem` could have a very small `_solve_lyap` method which dispatches between these standard implementations and which is called by `gramian`. If needed, on could then easily subclass `LTISystem` to hook in another Lyapunov solver. At the same time, `solve_lyap` could be easily called elsewhere. - If you feel this is needed, the dispatching code could be in `pymor.???.solve_lyap` which is then called by `LTISystem._solve_lyap`. However, I am still unsure what an appropriate place would be.

**Comment by pmli** [comment] 2016-11-08 16:05
Thanks for the detailed answer! You make a lot of good points. `LyapunovEquation` class definitely should be more easily modifiable.

I support your proposal about `bindings` and a small `_solve_lyap` method in `LTISystem` class (or maybe already in `InputOutputSystem`). I guess `LTISystem._solve_lyap` could be small enough without an additional `pymor.???.solve_lyap`.

pymess will not support MPI distributed parallelism any time soon, and, yes, pymess will be under GPL.

**Comment by sdrave** [comment] 2017-02-03 12:53
I have fixed now the test build on travis, by disabling tests when slycot/pymess is unavailable. However, we should start running these tests on travis as well. @pmli, regarding slycot: is there an official repository and/or release we want to use? We should also add an appropriate check in `pymor.core.config` to see if we have the right slycot version.

The last failing test is related to packaging and the `heat` jupyter notebook. @renemilk, how should we handle notebooks in general? I would guess that `REPO_ROOT/notebooks` or `REPO_ROOT/examples` would be a better place than `REPO_ROOT/src/pymorexamples`?

**Comment by pmli** [comment] 2017-02-03 13:07
The official slycot repository is in the python-control organization: https://github.com/python-control/Slycot
As for the release, they recently merged the H_infinity norm function (AB13DD) into master, so it would be ideal to use that. It seems the version number is 0.3.1, but on pip there is still 0.2.0.

**Comment by sdrave** [comment] 2017-02-06 11:28
Hi @pmli, I have now added a version test for slycot to `pymor.core.config` and added the current github master of slycot to `requirements-optional.txt`. With this, the slycot tests now run on travis. There are three failing tests, which I also experience on my machine. Maybe you can take a look?

**Comment by pmli** [comment] 2017-02-06 12:27
Strange... All slycot tests pass on my machine... The `heat.ipynb` is also working fine.
I'm using Numpy 1.12.0, if that means anything.

**Comment by sdrave** [comment] 2017-02-06 12:43
I also see this on my machine with Numpy 1.12.0. Interestingly, I have test_slycot[2-2-100], test_slycot_E[1-1-100], test_slycot_E[2-2-100] failing, both with an error of around 1e-8. Setting `OMP_NUM_THREADS=1` makes the first pass.

On travis, we have test_slycot[2-2-100], test_slycot_E[2-1-100] and test_slycot_E_trans[2-1-100] failing.

I am not sure about travis. My machine is currently using the manylinux numpy wheel which is shipping its own OpenBLAS. On the other hand, slycot is using my distro's OpenBLAS.

What is your setup?

**Comment by pmli** [comment] 2017-02-06 13:49
It seems to me I have the same BLAS setup (Numpy has it's own OpenBLAS, slycot uses my distro's OpenBLAS).

**Comment by sdrave** [comment] 2017-02-07 09:13
Ok, good to see that you have some way to reproduce this. Normally I would say that a small change of accuracy due to subtleties between different BLAS implementations or parallel vs. sequential code paths is acceptable. But here were are talking about two orders of magnitude, so this sounds more like a bug, doesn't it?

I guess we should first try to see if the difference in accuracy has something to do with BLAS or (probably more likely) slycot ...

**Comment by sdrave** [comment] 2017-02-07 09:50
On another machine I have 5 failing tests ...

**Comment by pmli** [comment] 2017-02-07 10:03
When I set `OMP_NUM_THREADS=1`, I get quite large relative residuals, of order 1e-2. I've tried running tests on my laptop, and some different tests failed. Again, with large residuals.

It's interesting that only (some) Riccati equation tests fail and Lyapunov tests pass...

**Comment by sdrave** [comment] 2017-06-29 12:37
Hi @pmli, I have now merged the reductor_objects branch into sys-mor in the sysmor-with-reductor-objects branch. I only did the minimal work necessary to get a somewhat consistent result. Please take a look. Of course, one might also think about making `bt`, etc., a class ...

**Comment by pmli** [comment] 2017-06-29 19:13
Hi @sdrave! This is really interesting. I think it makes sense to have a generic BT reductor, and then have different variants of BT inherit from it. I'll have to think about it some more, but this should make adding new BT variants much easier. Something similar for IRKA/TSIA should also be possible.

**Comment by sdrave** [comment] 2017-06-30 08:00
Good to hear that. I will then merge reductor_objects into master soon ..

**Comment by sdrave** [comment] 2017-11-21 13:44
I would propose this issue in favor of #412. Any objections, @pmli?

**Comment by pmli** [comment] 2017-11-21 15:36
@sdrave None at all.

**Closed** 2017-11-21 16:11 UTC
