### ISSUE TITLE
Debian doc packages have weird title

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#147] opened 2015-09-26 19:43 UTC
Our launchpad builds fail due to  b960c6ffa3d97bad5af6a8343423695ddc69127d. This can probably be fixed in a similar way as the readthedocs build (see 3a4ff7436ce88019c771944781b60dc43722b2ff). Also see http://stackoverflow.com/questions/13238736/how-to-document-cython-function-on-readthedocs. @renemilk, could you take a look at it?

**Comment by renemilk** [comment] 2015-10-01 08:26
The build itself works alright [again](https://launchpadlibrarian.net/219222277/buildlog_ubuntu-trusty-amd64.pymor_999.9.9~20150929~f7c29ce~daily~ubuntu14.04.1_BUILDING.txt.gz). I'll have a look at the generated docs package and  fix the recipe for new release series before closing this though.

**Comment by renemilk** [comment] 2015-10-01 09:18
Hmm. Content of the doc package looks fine and builds for ubuntu wiley work too. However the I'm attaching what looks like a regression to me (the version string): 
![version](https://cloud.githubusercontent.com/assets/47802/10217107/1362f09e-682e-11e5-8bdd-36304b496325.png)

**Comment by sdrave** [comment] 2015-10-01 12:04
Strange. With a local `make doc` I do not see this behaviour. Also, I have no idea what change could have caused this ...

**Comment by sdrave** [comment] 2015-10-07 09:07
The readthedocs build does not have the version string issue as well.

**Comment by sdrave** [comment] 2015-10-22 07:33
@renemilk, if you build the deb locally, do you get the same strange version string?

**Comment by renemilk** [comment] 2015-10-22 10:50
Yeah, I get it too. I guess that's an upside :smirk:

**Comment by sdrave** [comment] 2015-11-10 11:01
Do we know which commit caused the wrong version string?

**Comment by renemilk** [comment] 2015-11-11 15:34
Nope. But I guess I could bisect that at some point in time.

**Comment by renemilk** [comment] 2015-12-08 09:50
I failed to find a good commit bisecting on  my box. Can you confirm an OK doc.deb sometime along the line, @sdrave ?

**Closed** 2015-12-09 13:31 UTC
