### ISSUE TITLE
Qt.Py fails when both pyqt5 and pyside2 are installed

### ISSUE THREAD

**Issue by meretp** [pymor/pymor#1119] opened 2020-10-12 08:01 UTC
To use spyder for code development I have installed the package pyqt5 in my virtual environment. With it running `make docs` fails. The error starts with the following ImportError Warning and leads to a configuration error. It seems to me as there is some misunderstanding which qt installation to use.

> Qt.py [warning]: ImportError: /scratch/pymor_develop/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Core.so.5: version `Qt_5.15' not found (required by /scratch/pymor_develop/lib/python3.6/site-packages/PySide2/QtUiTools.abi3.so)

..

>Configuration error:
There is a programmable error in your configuration file:
Traceback (most recent call last):
  File "/scratch/pymor_develop/lib/python3.6/site-packages/sphinx/config.py", line 319, in eval_config_file
    execfile_(filename, namespace)
  File "/scratch/pymor_develop/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 89, in execfile_
    exec(code, _globals)
  File "/scratch/pymor_dev/src/docs/source/conf.py", line 30, in <module>
    gen_apidoc.walk(pymordemos)
  File "/scratch/pymor_dev/src/docs/source/gen_apidoc.py", line 53, in walk
    module = __import__(m, fromlist='none')
  File "/scratch/pymor_develop/lib/python3.6/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 146, in _import
    return original_import(name, *args, **kwargs)
  File "/scratch/pymor_dev/src/src/pymordemos/thermalblock_gui.py", line 44, in <module>
    from Qt import QtWidgets
  File "/scratch/pymor_develop/lib/python3.6/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 146, in _import
    return original_import(name, *args, **kwargs)
  File "/scratch/pymor_develop/lib/python3.6/site-packages/Qt.py", line 1913, in <module>
    _install()
  File "/scratch/pymor_develop/lib/python3.6/site-packages/Qt.py", line 1891, in _install
    our_submodule = getattr(Qt, name)
AttributeError: module 'Qt' has no attribute 'QtGui'

**Comment by renefritze** [comment] 2020-10-12 08:07
Thanks for the report @meretp! That indeed looks like `Qt.py` is confused and first loads pyqt and then misses pyside. Could you post the output of `pip freeze --all` so I can try to replicate this issue? 
Is it spyder that's executing the `make docs` or just plain from the terminal with your virtualenv activated?

**Comment by meretp** [comment] 2020-10-12 08:26
Just plain from the terminal.

The output of pip freeze:

>alabaster==0.7.12
apipkg==1.5
appdirs==1.4.4
argon2-cffi==20.1.0
astroid==2.4.2
atomicwrites==1.4.0
attrs==19.3.0
autopep8==1.5.4
Babel==2.8.0
backcall==0.2.0
bash-kernel==0.7.2
beautifulsoup4==4.9.1
bleach==3.1.5
certifi==2020.6.20
cffi==1.14.1
chardet==3.0.4
check-manifest==0.42
cloudpickle==1.5.0
cmarkgfm==0.4.2
codecov==2.1.9
colorama==0.4.3
coverage==5.2.1
cryptography==3.0
css-html-js-minify==2.5.5
cycler==0.10.0
Cython==0.29.21
decorator==4.4.2
defusedxml==0.6.0
diff-match-patch==20200713
diskcache==4.1.0
distlib==0.3.1
docopt-ng==0.7.2
docutils==0.16
entrypoints==0.3
execnet==1.7.1
filelock==3.0.12
flake8==3.8.3
future==0.18.2
helpdev==0.7.1
hypothesis==5.33.1
idna==2.10
imagesize==1.2.0
importlib-metadata==1.7.0
importlib-resources==3.0.0
iniconfig==1.0.1
intervaltree==3.1.0
ipydatawidgets==4.0.1
ipykernel==5.3.4
ipyparallel==6.3.0
ipython==7.16.1
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
jedi==0.17.1
jeepney==0.4.3
Jinja2==2.11.2
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.6
jupyter-console==6.2.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.6.3
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyter-sphinx==0.2.4
keyring==21.3.0
kiwisolver==1.2.0
lazy-object-proxy==1.4.3
lxml==4.5.2
Markdown==3.2.2
MarkupSafe==1.1.1
matplotlib==3.3.0
mccabe==0.6.1
meshio==3.3.1
mistune==0.8.4
more-itertools==8.4.0
mpi4py==3.0.3
mpmath==1.1.0
nbconvert==5.6.1
nbformat==5.0.7
nbresuse==0.3.6
notebook==6.1.1
numpy==1.19.1
numpydoc==1.1.0
packaging==20.4
pandocfilters==1.4.2
parso==0.7.0
pathtools==0.1.2
pep517==0.8.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.2.0
pip==20.2.3
pkginfo==1.5.0.1
pluggy==0.13.1
prometheus-client==0.8.0
prompt-toolkit==3.0.6
properties==0.6.1
psutil==5.7.2
ptyprocess==0.6.0
Pweave==0.30.3
py==1.9.0
pyamg==4.0.0
pybind11==2.5.0
pycodestyle==2.6.0
pycparser==2.20
pydocstyle==5.0.2
pyevtk==1.1.1
pyflakes==2.2.0
Pygments==2.6.1
pygmsh==6.0.2
pylint==2.5.3
pymess @ https://pymor.github.io/wheels/pymess-1.0.0-cp36-cp36m-manylinux1_x86_64.whl
-e git+git@github.com:meretp/pymor.git@8efdd6b15eb211cbb661d6e0df5fb6ab7ee2e597#egg=pymor
PyOpenGL==3.1.5
pyparsing==2.4.7
pypi-oldest-requirements==2020.4.2
PyQt5==5.12.3
PyQt5-sip==12.8.0
PyQtWebEngine==5.12.1
pyrsistent==0.16.0
PySide2==5.15.1
pytest==6.0.1
pytest-cov==2.10.1
pytest-forked==1.3.0
pytest-memprof==0.2.0
pytest-parallel==0.1.0
pytest-runner==5.2
pytest-timeout==1.4.2
pytest-xdist==2.1.0
python-dateutil==2.8.1
python-jsonrpc-server==0.3.4
python-language-server==0.34.1
python-slugify==4.0.1
pythreejs==2.2.0
pytz==2020.1
pyxdg==0.26
PyYAML==5.3.1
pyzmq==19.0.2
QDarkStyle==2.8.1
Qt.py==1.2.6
QtAwesome==0.7.2
qtconsole==4.7.6
QtPy==1.9.0
readme-renderer==26.0
requests==2.24.0
requests-toolbelt==0.9.1
requirements-parser==0.2.0
rfc3986==1.4.0
rope==0.17.0
rstcheck==3.3.1
scipy==1.5.2
SecretStorage==3.1.2
Send2Trash==1.5.0
setuptools==49.1.3
shiboken2==5.15.1
six==1.15.0
slycot==0.4.0
snowballstemmer==2.0.0
sortedcontainers==2.2.2
soupsieve==2.0.1
Sphinx==3.2.0
sphinx-material==0.0.30
sphinx-qt-documentation==0.3
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
spyder==4.1.5
spyder-kernels==1.9.4
spyder-reports==0.1.1
sympy==1.6.2
tblib==1.7.0
terminado==0.8.3
testipynb==0.0.2
testpath==0.4.4
text-unidecode==1.3
toml==0.10.1
torch==1.6.0
tornado==6.0.4
tqdm==4.48.2
traitlets==4.3.3
traittypes==0.2.1
twine==3.2.0
typed-ast==1.4.1
ujson==1.35
Unidecode==1.1.1
urllib3==1.25.10
virtualenv==20.0.31
watchdog==0.10.3
wcwidth==0.2.5
webencodings==0.5.1
wheel==0.34.2
widgetsnbextension==3.5.1
wrapt==1.12.1
wurlitzer==2.0.1
yapf==0.30.0
zipp==3.1.0

**Comment by renefritze** [comment] 2020-10-12 10:26
Thanks! I can replicate the problem now. There's an easy workaround. If you set `export QT_PREFERRED_BINDING=PyQt5:` (or `export QT_PREFERRED_BINDING=PySide2:`) before `make docs` the build should go through. Note the trailing `:`.  
The same problem will also pop up if you try to run some of the demos. 
The issue is not fixed in newer `Qt.py` versions. 
Not yet sure how we can fix this properly, since hardcoding a single preferred binding pretty much defeats the purpose of us using the `Qt.py` shim.

**Comment by meretp** [comment] 2020-10-12 10:44
'export QT_PREFERRED_BINDING=PyQt5:' works for me. With PySide2 I still get the error. Thanks!

**Comment by renefritze** [comment] 2020-10-13 09:28
Turns out matplotlib is the culprit. If we import `Qt.py` before `matplotlib` all is well. Other way round is broken. 
The easiest way to ensure this would IMO be to create a tiny pymor_mpl shim around matplotlib and mandate to import mpl stuff from there and prohibit direct import of matplotlib elsewhere. I a;so have the creeping feeling that we've been in a similar situation before...
Opinions, @pymor/pymor-devs ?

**Comment by renefritze** [comment] 2020-10-13 15:08
Found it:
https://github.com/pymor/pymor/commit/106be0eed3ed4d2c0366dd6bf86cbc4f5ec4486f

**Comment by sdrave** [comment] 2020-10-30 09:40
How shall we proceed here @renefritze?

**Comment by renefritze** [comment] 2020-10-30 09:44
I think we should do two things: 
 1. short term (next release) workaround: import qtpy in the MPL config check 
 2. long term (future) look into the actual mismatch loading between MPL, diff qt abstractions and potentially upstream a Fix

**Comment by sdrave** [comment] 2020-10-30 10:13
Sounds reasonable.

**Comment by renefritze** [comment] 2020-11-04 09:45
Workaround will be merged soon and the CI pipelines now install both pyside2 and pyqt5.

**Comment by renefritze** [comment] 2020-11-04 12:15
Moving to 2021 release for the remaining long term fix.

**Comment by renefritze** [comment] 2021-05-05 08:48
Superseded by #1303

**Closed by renefritze** 2021-05-05 08:48 UTC
