### ISSUE TITLE
Symmetric problem has non symmetric solution

### ISSUE THREAD

**Issue by andreasbuhr** [pymor/pymor#328] opened 2016-12-06 19:38 UTC
I set up a symmetric problem. pymor gives a non symmetric solution. It's just the poisson equation with homogeneous Dirichlet boundary conditions and a symmetric right hand side.

The solution has a value range [-0.468, 0.482], so the difference between min and max is 0.014.

Screenshot:
![screen](https://cloud.githubusercontent.com/assets/3892222/20940621/b8f1796c-bbf3-11e6-91b7-56040ec0f3c9.png)

reproducer for pymor 0.4.
[bugreport.zip](https://github.com/pymor/pymor/files/634838/bugreport.zip)

**Comment by sdrave** [comment] 2016-12-06 20:31
Have you checked if the data function is aligned with the grid? Does the solution become symmetric when the grid is refined?

**Comment by andreasbuhr** [comment] 2016-12-07 07:54
The data is aligned with the grid. 
But this should not have any influence as a symmetric rhs with a symmetric grid should always lead to a symmetric solution, shouldn't it?

The symmetry gets better when the grid is refined.

However, I found an asymmetry: At y=0.5, the intervals of the rhs are:
0 on [0, 0.02)
-127 on [0.02,  0.1)
0 on [0.1, 0.9)
127 on [0.9, 0.98)
0 on [0.98, 1]

So the intervals are open at their upper end, which lies exactly on grid lines  (for a 100x100 grid). 
Is the rhs first interpolated into the discrete space before being used? This could explain this behaviour.

**Comment by sdrave** [comment] 2016-12-07 09:39
Ok, I have just checked this: The RHS is assembled using a quadrature, and by default, the default quadrature of order 2 is chosen. For the triangle reference element, the quadrature points lie on the edge centers, which explains the observed behavior. Setting the order to 1 produces a symmetric solution symmetric.

Thus, I would say this is not a bug.

**Comment by sdrave** [comment] 2016-12-07 09:40
Although one should double-check whether 2 is a good default quadrature order.

**Comment by sdrave** [comment] 2016-12-20 19:53
@andreasbuhr, if I remember correctly, you are planning to provide some quadratures which do not evaluate the integrand at the element boundaries, solve this unexpected behavior in most cases? Maybe we should open a new issue for this?

**Comment by sdrave** [comment] 2017-05-08 13:36
@andreasbuhr, since this is not really a bug in pyMOR, I will close this issue for now. However, a PR with improved quadratures is welcome ...

**Closed by sdrave** 2017-05-08 13:36 UTC
